#!/usr/bin/env python3
"""Create a GitHub PR from the current branch against origin/main."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path


def run(args: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, text=True, capture_output=True, check=check)


def git(args: list[str], *, check: bool = True) -> str:
    result = run(["git", *args], check=check)
    return result.stdout.strip()


def require_clean_context() -> None:
    try:
        git(["rev-parse", "--is-inside-work-tree"])
    except subprocess.CalledProcessError:
        sys.exit("Not inside a git repository.")

    branch = git(["branch", "--show-current"])
    if not branch:
        sys.exit("Current checkout is detached; create or switch to a branch first.")
    if branch in {"main", "master"}:
        sys.exit(f"Refusing to open a PR from {branch!r}. Switch to a feature branch first.")


def command_available(name: str) -> bool:
    return run(["sh", "-c", f"command -v {name}"], check=False).returncode == 0


def collect_summary(base: str) -> dict[str, str]:
    git(["fetch", "origin", "main"])
    compare = f"{base}...HEAD"
    return {
        "branch": git(["branch", "--show-current"]),
        "compare": compare,
        "status": git(["status", "--short", "--branch"]),
        "commits": git(["log", "--oneline", "--decorate=no", compare], check=False),
        "stat": git(["diff", "--stat", compare], check=False),
        "files": git(["diff", "--name-status", compare], check=False),
    }


def infer_title(summary: dict[str, str]) -> str:
    first_commit = summary["commits"].splitlines()[0] if summary["commits"] else ""
    if first_commit:
        return first_commit.split(" ", 1)[1]
    return summary["branch"].replace("-", " ").replace("_", " ").capitalize()


def build_body(summary: dict[str, str], tests: str) -> str:
    files = summary["files"] or "No file changes detected."
    commits = summary["commits"] or "No commits detected in comparison range."
    stat = summary["stat"] or "No diff stat available."
    test_line = tests if tests else "Not run; generated by helper script without executing project checks."

    return f"""## Summary
- Compare `{summary["branch"]}` with `origin/main`.
- Review the changed files and commits below before submitting.

## Changed files
```text
{files}
```

## Commits
```text
{commits}
```

## Diff stat
```text
{stat}
```

## How to test
- {test_line}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", default="origin/main", help="Base ref to compare against.")
    parser.add_argument("--title", help="PR title. Defaults to the first commit subject.")
    parser.add_argument("--tests", help="How-to-test line to include in the PR body.")
    parser.add_argument("--dry-run", action="store_true", help="Print the PR command and body without opening a PR.")
    parser.add_argument("--no-push", action="store_true", help="Do not push the branch before creating the PR.")
    args = parser.parse_args()

    require_clean_context()
    summary = collect_summary(args.base)
    title = args.title or infer_title(summary)
    body = build_body(summary, args.tests or "")

    if args.dry_run:
        print(f"Title: {title}")
        print(f"Base: main")
        print(f"Head: {summary['branch']}")
        print()
        print(body)
        return 0

    if not command_available("gh"):
        sys.exit("GitHub CLI (`gh`) is not available on PATH.")

    if not args.no_push:
        run(["git", "push", "-u", "origin", "HEAD"])

    with tempfile.NamedTemporaryFile("w", delete=False, suffix="-pr-body.md") as handle:
        handle.write(body)
        body_path = Path(handle.name)

    try:
        result = run(
            [
                "gh",
                "pr",
                "create",
                "--base",
                "main",
                "--head",
                summary["branch"],
                "--title",
                title,
                "--body-file",
                os.fspath(body_path),
            ],
            check=False,
        )
        if result.stdout:
            print(result.stdout.strip())
        if result.stderr:
            print(result.stderr.strip(), file=sys.stderr)
        return result.returncode
    finally:
        body_path.unlink(missing_ok=True)


if __name__ == "__main__":
    raise SystemExit(main())
